### PR TITLE
Showcase on how to use all the hardware features of the badge

### PR DESCRIPTION
**Pull request by nicolan**

### CODE REVIEW

**Review by marcmerlin — COMMENTED** [review]
I like this, well done!
@geekscape worth merging IMO

**Comment by marcmerlin** [comment]
@nicolan , I did reboot and run this again. Init seems to cause problems now:
```
>>> import examples.showcase as showcase
>>> showcase.initialise()
>>> ### WiFi: Checking WiFi configuration with available networks
I (277198) network: event 1
### MQTT: Disconnected by mqtt_thread
### MQTT: Disconnected by connect
### MQTT: Disconnected by connect
loops forever
```

**Comment by marcmerlin** [comment]
I did  however notice that it says Wifi false when Wifi is connected.
MQTT also says false, but I think that one is indeed false (I can't send MQTT commands)

**Comment by geekscape** [comment]
The Aiko framework looks after initializing LEDs, OLEDs, Wi-Fi network and MQTT ... so, the initialise() function should be remove and not used.  I'll fix that up.
Also, this example should be updated to use the [recent Aiko framework button / touch slider](https://github.com/geekscape/aiko_engine_mp/blob/master/lib/aiko/button.py) support.

**Comment by geekscape** [comment]
I've tidied up this example.

**Pull request merged**
