### PR TITLE
Add example - examples/oled_eyes.py

### PR DESCRIPTION
**Pull request by PaulSchulz**
Draws some circles on oled display as eyes. They don't move yet.

### CODE REVIEW

**Review by marcmerlin — COMMENTED** [review]
it's a bit moody for me (doesn't always draw a full disk), but I got it to work, although the eyes never moved for me.
Is it possible to re-use existing drawing libraries for micropython to save ourselves the trouble of writing lines, circles, discs and so forth, pixel by pixel?

**Comment by marcmerlin** [comment]
I believe you an import and use adafruit::gfx:  https://learn.adafruit.com/micropython-displays-drawing-shapes/software

**Comment by marcmerlin** [comment]
I also found this in the ssd1306 init, so there are basic primitives (although no circles or disks)
```
        self.fill = fb.fill
        self.pixel = fb.pixel
        self.hline = fb.hline
        self.vline = fb.vline
        self.line = fb.line
        self.rect = fb.rect
        self.fill_rect = fb.fill_rect
        self.text = fb.text
        self.scroll = fb.scroll
        self.blit = fb.blit
```

**Comment by geekscape** [comment]
hi @PaulSchulz and @marcmerlin ... since you have both now written an example each that has "eyes".  Do you mind collaborating to produce one example that is the synthesis of the best of both your examples, please ?

**Comment by marcmerlin** [comment]
Hi @PaulSchulz  your code gave me the idea to write mine.
Mine is 100% different in implementation, though, 
See https://github.com/geekscape/aiko_engine_mp/tree/master/examples/blinkeye
and
https://www.youtube.com/watch?v=DJnniyPrRqs

Paul, I think your example still makes sense, you could totally do something similar that uses drawing primitives only as opposed to bitmaps. It's a fair amount of work (then again, so was mine :) ), but it would be cool to see another way to do this.

**Comment by PaulSchulz** [comment]
I like yours better :-)

**Pull request closed without merging**
